//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceService._1___Implementation
{
    using System;
    
    public enum Kursstatus : int
    {
        Geplant = 0,
        FindetStatt = 1,
        Vorbei = 2,
        Abgesagt = 3
    }
}
