//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceService._1___Implementation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rechnung()
        {
            this.Rechnungspositionen = new HashSet<Rechnungsposition>();
            this.AbrechnungsZeitraum = new AbrechnungsZeitraumTyp();
        }
    
        public int Rechnungsnummer { get; set; }
        public bool Bezahlt { get; set; }
    
        public AbrechnungsZeitraumTyp AbrechnungsZeitraum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechnungsposition> Rechnungspositionen { get; set; }
        public virtual Kunde Kunde { get; set; }
    }
}
