//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenceService._1___Implementation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnungsposition
    {
        public int Rechnungspositionsnummer { get; set; }
        public decimal Kosten { get; set; }
    
        public virtual Kurs Kurs { get; set; }
    }
}
